apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: csr-for-gk
spec: 
  groups:
  - system:authenticated
  usages: 
  - digital signature
  - key encipherment
  - client auth
  signerName: kubernetes.io/kube-apiserver-client  
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1VqQ0NBVG9DQVFBd0RURUxNQWtHQTFVRUF3d0NaMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUURBOE9xUFhqakt5QkZBQVFEVEhuUWVoNVZERXFsSjBhVCtwVUV6dnZLSkh6NTNleFJvCjJTb2lCY2lzQ1dsTWZwNmNCbHF6WFQ0MnUwSU03ZFlzUTB0T3liU1hrV2ZScThhWHE0NXVrV3VjTWhBNkN1VFgKNTJhUzZONGxJZG5MSTYrdzdaanpsOUw5bVNqSGRTL3l2b2hiR0g5RGpEaFpEODNhbDVQR3kzRFQ1a00ySUtQUgp4KzJMQW1GTndYNytMNzlaU0tPeUpnQmdySnFJS0ZLb1JxcTBaUGZGR0J0TVhTMk9JbGVwd1RPMHZoUVNOaDluCkJYSDNLZEp1OUxCR0cyaC82empISzg0SHNXSUhyaGVOWDd1Y1dPYXRSS01nREkxajU3Y0NMbllDSTJoVUkwYlEKUXliVll5Qi9lUXU4MjErTnhlditObjNMdEVEcmhuYmNaZXM3QWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQWFwaE1IbHdPWTdJTUNwcmM1R1JPN0lDZWJ1dnF1QjhlYmRCcDVXT3FuQUwrU0pRUUREL0FveEp1CjJiamkrVzJrZUFWdXVrc2pGYmROVld2ZmVzZkxYUkM5bEhiVE9nVGswU0EybC9oRXJWZHNwYzBHcmp3dWtFMUIKNkZYdkZKNWZWOVZYYnpHREozRWc5SWp5R3RFWHQrZ01DOGZnbFhaUFVYTm91ZEQ0c1N3Y2hVeEFGdDBldWpHeApmS2o3bDZBL2k4QjZDRGEvNlpGWGVMZ0RwL01mbGNqc2pUTFRQTWdxTk1jbGg0bTlSMFRIZ1YwQnQ4dVpFQmlMCm9heUpvUmxkdUlVQzQzb0pEclhaSlg0UUZpRGI1U0t3b1g0RFBDR2lEZDlzSVJwNjNaWHZWNjhBY1BMb0lSNFQKV25haXVBSFpVb24veFVnRHgrYk5MNmRtSjFlK1JBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==

