apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gk-developer-binding
subjects:
- kind: User
  name: gk # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
